
@host = http://localhost:3000
@urlUsers = /api/users
@urlAdmins = /api/admins
@urlShows = /api/shows
@urlAudios = /api/audios
@urlCharacters = /api/characters
@urlStore = /api/store


##### USERS API #####
# GET http://localhost:3000/api/users
GET {{host}}{{urlUsers}}

### GET/api/users/1
GET {{host}}{{urlUsers}}/2

### create/api/users/
POST {{host}}{{urlUsers}}
Content-Type: application/json

{ 
    "name": "Sofia", 
    "surname": "Paez", 
    "age": "24", 
    "dni": "0000082", 
    "email":"sof@gmail.com", 
    "phone": "9543007056",
    "address":"12777 nw avenue",
    "password":"pass123",
    "role":"admin"
}

###update/api/users/:userId
PUT {{host}}{{urlUsers}}/update/2
Content-Type: application/json

{ 
    "name":"Joan", 
    "surname": "Paez", 
    "age": 24, 
    "dni": "000008",
    "email":"sofy@gmail.com", 
    "phone": 9543007056, 
    "address":"12777 nw avenue", 
    "password":"pass1256", 
    "role":"admin"
}

###delete/api/users/:userId
DELETE {{host}}{{urlUsers}}/6

####### REGISTER & LOGIN ########
### Register one user:
# POST /api/users/register
POST {{host}}{{urlUsers}}/register
Content-Type: application/json

{
    "name":"Pika", 
    "surname": "Chu", 
    "age": 11, 
    "dni": "1111111X",
    "email":"pica@gmail.com", 
    "phone": 1111111, 
    "address":"11 nw avenue", 
    "password":"1111", 
    "role":"user"
}




##### SHOWS API #####
### Return all shows:
# GET /api/shows/
GET {{host}}{{urlShows}}

### Return shows by name:
# GET /api/shows/:title
{{host}}{{urlShows}}/program3

#### AUDIOS API #####
### Return all audios: 
# GET /api/audios/
GET {{host}}{{urlAudios}}

### Return audio by title:
# GET /api/audios/:title
GET {{host}}{{urlAudios}}/music1

### Return audio by showId:
# GET /api/audios/shows/:showId
GET {{host}}{{urlAudios}}/shows/1

#### CHARACTERS API #####
### Return all characters:
# GET /api/characters/
GET {{host}}{{urlCharacters}}

### Return character by name:
# GET /api/characters/:characterName
GET {{host}}{{urlCharacters}}/Samaya

### Return character by showId:
# GET /api/characters/shows/:showId
GET {{host}}{{urlCharacters}}/shows/1

#### STORE API #####
### Return all products:
# GET /api/store/
GET {{host}}{{urlStore}}

### Return product by name:
# GET /api/store/:name
GET {{host}}{{urlStore}}/phone

### Return product ordered from min to max price:
# GET /api/store/order/desc
GET {{host}}{{urlStore}}/order/desc

### Return product ordered from max to min price:
# GEE /api/store/order/ASC
GET {{host}}{{urlStore}}/order/asc

### Return product by status:
# GET /api/store/status/:productStatus
GET {{host}}{{urlStore}}/status/pending







