
@host = http://localhost:3000
@urlUsers = /api/users
@urlAdmins = /api/admins
@urlShows = /api/shows
@urlAudios = /api/audios
@urlCharacters = /api/characters
@urlStore = /api/store


##### USERS API #####
# GET http://localhost:3000/api/users
GET {{host}}{{urlUsers}}

### GET/api/users/1
GET {{host}}{{urlUsers}}/2

###GET/api/users/role
GET {{host}}{{urlUsers}}/admin

### create/api/users/
POST {{host}}{{urlUsers}}
Content-Type: application/json

{ 
"name": "Paul", 
"surname": "Paez", 
"age": "24", 
"dni": "000908", 
"email":"paul@gmail.com", 
"phone": "9543007059",
"address":"12777 nw avenue",
"password":"pass123",
"role":"admin"
}

###update/api/user/:userId
PUT {{host}}{{urlUsers}}/update/2
Content-Type: application/json

{ 
"name": "Sofia", 
"surname": "Paez", 
"age": "24", 
"dni": "000087", 
"email":"hl9@gmail.com", 
"phone": "9543087006", 
"address":"12777 nw avenue", 
"password":"pass1256", 
"role": "admin"
}

###delete/api/user/:userId
DELETE {{host}}{{urlUsers}}/1

###


##### SHOWS API #####
### Return all shows:
# GET /api/shows/
GET {{host}}{{urlShows}}

### Return shows by name:
# GET /api/shows/:title
{{host}}{{urlShows}}/program3

#### AUDIOS API #####
### Return all audios: 
# GET /api/audios/
GET {{host}}{{urlAudios}}

### Return audio by title:
# GET /api/audios/:title
GET {{host}}{{urlAudios}}/music1

### Return audio by showId:
# GET /api/audios/shows/:showId
GET {{host}}{{urlAudios}}/shows/1

#### CHARACTERS API #####
### Return all characters:
# GET /api/characters/
GET {{host}}{{urlCharacters}}

### Return character by name:
# GET /api/characters/:characterName
GET {{host}}{{urlCharacters}}/Bonnie Cella

### Return character by showId:
# GET /api/characters/shows/:showId
GET {{host}}{{urlCharacters}}/shows/2

#### STORE API #####
### Return all products:
# GET /api/store/
GET {{host}}{{urlStore}}

### Return product by name:
# GET /api/store/:name
GET {{host}}{{urlStore}}/phone

### Return product ordered from min to max price:
# GET /api/store/order/desc
GET {{host}}{{urlStore}}/order/desc

### Return product ordered from max to min price:
# GEE /api/store/order/ASC
GET {{host}}{{urlStore}}/order/asc

### Return product by status:
# GET /api/store/status/:productStatus
GET {{host}}{{urlStore}}/status/pending







